### ISSUE TITLE
[Bug?] translations get warnings about adding/removing `{}`

### ISSUE THREAD

**Issue by TrueBrain** [TrueBrain/nile-library#11]
Sometimes translations add or remove a `{}`, as they need / don't want a newline.

This is currently a warning.

I am unsure if we should allow this behaviour or not, but mostly mentioning that as it is different from eints.

@frosch123 what do you think?

**Comment by frosch123** [comment]
Yes, this is new in nile.
Translators are supposed to not change the general formatting of strings, like colours, fonts, special icons, ...
I included "new line" into this rule.
I have some stashed/unfinished validations, which check whether each command (like `{NUM}`) is printed with the same colour in the translation as in the base language. The same check would also validate that the same info is on the same line.
Time will tell, whether there are valid reasons for translations to differ.

**Comment by TrueBrain** [comment]
Okiedokie. Maybe we should write down these changes, as to inform translators of that during eints -> nile transition. Just so they understand why now all of a sudden it is an issue :)

On the positive side, it does show one string in both Dutch and German that is wrong. As in, they only translated the first line, never the second :)
